[package]
name = "movement-token-tutorial"
version = "1.0.0"
authors = []

[addresses]
movement_token_tutorial = "_"

[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/movementlabsxyz/aptos-core.git"
rev = "movement"
subdir = "aptos-move/framework/aptos-framework"
